### ISSUE TITLE
post-mortem note

### ISSUE THREAD

**Issue by mmaulwurff** [Blue-Shadow/nchud#37]
If anyone decides to fork and continue this project or to create a spiritual successor to NC HUD, it would help greatly to know why the project was [discontinued](https://forum.zdoom.org/viewtopic.php?f=45&t=33079&start=495#p1191029).

The questions are:
- what would you do differently?
- what parts of HUD turned out to be not to be as planned?
- what obstacles were in the way?
- what features did you want to implement, but couldn't?

**Comment by Blue-Shadow** [comment]
What I have in mind is starting fresh, going back to basics, and focusing on end-user experience rather than modibility. I really felt that the patches hampered my ability to do things; whenever I wanted to change something, there's the patches that I needed to worry about. They're a weight that I had to carry. Yes, I know, the majority change icons. But still, they created "noise", a distraction that prevented me from focusing on the HUD itself.

When I rewrote the HUD in ZScript back in 2017, I thought patches were a thing of the past, but apparently I was wrong.
